### ISSUE TITLE
Add more countries

### ISSUE THREAD

**Issue by mannuelf** [mannuelf/nuc-studio-1-project-frontend#12]
# Add more countries 

To add countries to system, a polygon must be added to the constants file and integrated.

https://github.com/mannuelf/nuc-studio-1-project-frontend/blob/main/src/js/models/getPolygon.ts#L6
https://github.com/mannuelf/nuc-studio-1-project-frontend/blob/main/src/js/config/polygons.ts#L10

**Comment by srdjanf** [comment]
Code finished and working. Still a lot of room for improvement.
